dist: xenial

language: node_js

services:
    - docker

env:
    - DOCKER_COMPOSE_VERSION=1.4.2

node_js:
    - "lts/dubnium"

install:
    - yarn

before_script:
    - yarn build
    - (cd example && yarn)

script:
    - yarn test:ci
